# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb8bd7a2487830149f4bfc4f7affe298d7b1de08d46a4a249fcb8f898e91cd0534022f501284d44dd25541eb01fd14f7af3e8413ab09d9294746ea2e29d15581

test:
  secret_key_base: 9fb5064cfaf7e7b29dc47304933e7595b93138c94f751850cd0191ee8ae64060248061486196b04c4cb4de08d0c8584e5be3a8adda714d36d0af052d31ebde6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
